### ISSUE TITLE
Patreon Issue 

### ISSUE THREAD

**Issue by justSelim** [Cody47/Insta47-for-iOS#3]
Hey Cody47, I have an issue. I tried to sideload all the time but it always asks me for patreon. Is there any other solution?

**Comment by Cody47** [comment]
@justSelim its a known issue after v330.0, there's a temporary workaround fix for this:
1. Disconnect Patreon under Manage License regram with the current install ipa
2. Uninstall the current disconnected patreon IG ipa
3. Download IG v330.0 and connect patreon on that ipa
4. Download, sign and install the latest ipa crack link above and login your IG account as usual
5. Go to ReGram setting > Manage License > Connect Patreon Login via email > Click “Manage Subs” and join dev Patreon > ReGram cracked done !

**Comment by justSelim** [comment]
Thanks Cody, it worked! If there is any way to support your contribution please let us know 🤍

**Comment by Cody47** [comment]
> Thanks Cody, it worked! If there is any way to support your contribution please let us know 🤍

@justSelim good to know that bruh, yeah you can support me here : [buymeacoffee](https://buymeacoffee.com/cody47), [paypal](https://paypal.me/belyksahil)
