### ISSUE TITLE
Got 'The name “Insta⁴⁷” contains invalid characters.' error while sideloading using altstore

### ISSUE THREAD

**Issue by notnk** [Cody47/Insta47-for-iOS#4]
The name “Insta⁴⁷” contains invalid characters.
is popping up when i try to sideload the app 
im using ios 18 btw 

(3009) The name for this app is invalid.
AltStore.AppleDeveloperError

AltStore couldn’t register an App ID with Apple because the app name contains non-ASCII characters. You can try downloading from another source.

this is what altstore is showing

**Comment by Cody47** [comment]
@notnk Try changing app's name and then try to sideload

**Comment by notnk** [comment]
That also i tired but didnt workOn 11 Sep 2024, at 7:26 AM, Sahil Yaduvanshi ***@***.***> wrote:﻿
@notnk Try changing app's name and then try to sideload

**Comment by Cody47** [comment]
> @notnk Try changing app's name and then try to sideload
try changing the name of the app with esign and then sideload
