### ISSUE TITLE
Hide reels, stories, posts, suggested posts on search page etc.

### ISSUE THREAD

**Issue by haja-fgabriel** [Cody47/Insta47-for-iOS#6]
There is this really cool project called Distraction Free Instagram at https://www.[distractionfreeapps.com](https://www.distractionfreeapps.com/)/. However, it is only available on Android.

What I propose is to replicate its features in this mod for Instagram, since it is a good foundation.

**Comment by Cody47** [comment]
ayo tf is this, if you need those features on iOS, I would suggest you to simply uninstall the app its as simple as that!

**Comment by haja-fgabriel** [comment]
I already uninstalled the app and use a browser extension to hide the feed and the stories, but I can’t see some photos people send me because it tells me to open from the app
