### ISSUE TITLE
V4.0

### ISSUE THREAD

**Issue by goffena** [Cody47/Insta47-for-iOS#8]
Thanks for your update
But I can’t sideload

it will popup error message 
![IMG_7513](https://github.com/user-attachments/assets/02100881-be4a-404e-b001-e655ad829608)
![IMG_7514](https://github.com/user-attachments/assets/c3839bd2-7f58-4f60-bdda-6a5f99402205)

can you look into it what happen inside your bundle?
Thanks

**Comment by Cody47** [comment]
@goffena can’t understand the logs, can you provide me proper logs? also try sideloading it using esign or sideloadly

**Comment by goffena** [comment]
It just show this error code: AltServer.ExceptionError 0
The message is total scramble message (maybe because I’m under mandarin environment)
Let me try to use English version and try again

**Comment by goffena** [comment]
under English and use altstore again, same message again... thanks for your support, i try sideloadly later

**Comment by goffena** [comment]
sideloadly is fine, great thanks
